// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANCUP0L_RvZ-9qlV7hu3WQIfQo5GObnEk',
    appId: '1:394803825107:web:4fefd3e18a1a2c4b73c726',
    messagingSenderId: '394803825107',
    projectId: 'pwa-caht',
    authDomain: 'pwa-caht.firebaseapp.com',
    storageBucket: 'pwa-caht.firebasestorage.app',
    measurementId: 'G-0CVN6J5NG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs9xqEyh_NXw-PyFZiVJ5bL26bYu4chnQ',
    appId: '1:394803825107:android:e8f78e2c7a1aa89a73c726',
    messagingSenderId: '394803825107',
    projectId: 'pwa-caht',
    storageBucket: 'pwa-caht.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYNu7pxz9f4Ba5urMlPUpvhtYPYtYuCm0',
    appId: '1:394803825107:ios:37dc7b46064a8a9c73c726',
    messagingSenderId: '394803825107',
    projectId: 'pwa-caht',
    storageBucket: 'pwa-caht.firebasestorage.app',
    iosBundleId: 'com.example.pwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYNu7pxz9f4Ba5urMlPUpvhtYPYtYuCm0',
    appId: '1:394803825107:ios:37dc7b46064a8a9c73c726',
    messagingSenderId: '394803825107',
    projectId: 'pwa-caht',
    storageBucket: 'pwa-caht.firebasestorage.app',
    iosBundleId: 'com.example.pwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANCUP0L_RvZ-9qlV7hu3WQIfQo5GObnEk',
    appId: '1:394803825107:web:af2a982c73995b9073c726',
    messagingSenderId: '394803825107',
    projectId: 'pwa-caht',
    authDomain: 'pwa-caht.firebaseapp.com',
    storageBucket: 'pwa-caht.firebasestorage.app',
    measurementId: 'G-HW01HGZCVY',
  );
}
